config/routes.rb
Codemart2::Application.routes.draw do
  
  get "pages/main/:id", :as => "add_to_cart", :controller => "pages", :action => "add_product"
  get "pages/remove_from_cart/:cart_index", :as => "remove_from_cart", :controller => "pages", :action => "remove_from_cart"

  root :to => "pages#main"
  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def main
    @products = Product.all
  end
  
  def add_product
    if session[:cart]
      session[:cart] << params[:id]
    else
      session[:cart] = Array.new
      session[:cart] << params[:id]
    end
        redirect_to root_url
  end
    
    def remove_from_cart
      session[:cart].delete_at(params[:cart_index].to_i)
      if session[:cart].count == 0
        reset_session
      end
      redirect_to root_url
    end
    
end
#problem encountered was that an 'end' tag was missing!!!!!!!

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codemart2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_products.html.erb
<% @products.each do |product| %>
                     <%= product.name %> | <%= product.description %> | <%= number_to_currency(product.price) %> ==> <%= link_to "Add to Cart", add_to_cart_url(product.id) %><br>

<% end %>

app/views/pages/_shopping.html.erb
<% session[:cart].each_index do |cart_index| %>
  <%= Product.find(session[:cart][cart_index]).name %> | <%= link_to "Remove from Cart", remove_from_cart_url(cart_index) %><br>
<% end %>

app/views/pages/main.html.erb
<div class="content-outer" id="header_home">
				<div class="diamond-left">
					<div class="diamond-right">
						<div class="content-inner">													
							<div class="top">
								<div class="left">
									
								</div>
								<p>
								<div class="left">
								  <% if session[:cart] %>
								    <p><span class="or">  Your Cart Contents: </span><br>
								      
								       <span class="cufon">
								         <%= render :partial => 'shopping' %>
								       </span> </p>
								  <% end %>
									<p> <span class="or">Items for Sale: </span> <br> <span class="cufon">
									 
									 <%= render :partial => 'products' %>

									 
									</span> </p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>